name: currency_picker
description: A flutter package to select a currency from a list of currencies.

homepage: https://github.com/Daniel-Ioannou
repository: https://github.com/Daniel-Ioannou/flutter_currency_picker

version: 1.0.6

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  collection: ^1.15.0-nullsafety.4
  flutter:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.2

flutter:
